from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://id.fieldnation.com/login?client_id=5PUz4s3nEwH3&redirect_uri=https%3A%2F%2Fapp.fieldnation.com%2F.ambassador%2Foauth2%2Fredirection-endpoint&response_type=code&scope=openid&state=96e18bc4addab6dd181f2560a17cf97384f3f5f19538c88d2d3fd69446487287%3Ahttps%3A%2F%2Fapp.fieldnation.com%2Fworkorders")
    page.get_by_label("Username / Login").click()
    page.get_by_label("Username / Login").fill("esanchez@machnetworks.com")
    page.get_by_role("button", name="Continue", exact=True).click()
    page.get_by_label("Password").click()
    page.get_by_label("Password").fill("")
    page.get_by_role("button", name="Log in").click()
    
    
    page.goto("https://app.fieldnation.com/workorders")
    page.get_by_role("button", name="Manage", exact=True).click()
    page.get_by_role("link", name="Clients").click()
    page.goto("https://app.fieldnation.com/clients")
    page.locator(".GridColumn--xs-12__VUQw0").click()
    page.get_by_placeholder("Search…").fill("k1 speed")
    page.get_by_placeholder("Search…").press("Enter")
    page.get_by_role("button", name="List").click()
    page.get_by_text("17221 Von Karman Ave").click()
    page1 = context.new_page()
    page1.goto("https://app.fieldnation.com/clients/622454/edit")
    page1.get_by_test_id("ClientTitle").click()
    page1.get_by_test_id("ClientTitle").fill("WI - K1 Speed - Irvine")
    page1.get_by_test_id("Save Changes").click()
    page2 = context.new_page()
    page2.goto("https://app.fieldnation.com/workorders/create?client_id=622454&simple-create=1")
    page2.get_by_test_id("templateDropdown").locator("span").nth(3).click()
    page2.get_by_label("Site Survey", exact=True).click()
    page2.get_by_test_id("advancedWorkOrderTitle").fill("TELEPHONE Tech - Site Survey - POTS to Wireless - K1 Speed - Irvine")
    page2.get_by_label("Display name").click()
    page2.get_by_label("Display name").fill("K1 Speed - Irvine")
    page2.get_by_test_id("address1").click()
    page2.get_by_test_id("address1").fill("17221 Von Karman Ave")
    page2.get_by_test_id("city").click()
    page2.get_by_test_id("city").fill("Irvine")
    page2.locator("#stateSelect span").nth(2).click()
    page2.get_by_label("California").click()
    page2.get_by_label("Zip Code").click()
    page2.get_by_label("Zip Code").fill("92614")
    page2.get_by_placeholder("MM/DD/YYYY").click()
    page2.get_by_label("Choose Tuesday, August 1st, 2023").click()
    page2.locator("#exactDatePickers").get_by_role("textbox").nth(1).fill("9:00am")
    page2.locator("#exactDatePickers").get_by_role("textbox").nth(1).click()
    page2.get_by_test_id("additionalContact_1").get_by_label("Name or Description").fill("Kali Morris")
    page2.get_by_test_id("additionalContact_1").get_by_label("Phone").click()
    page2.get_by_test_id("additionalContact_1").get_by_label("Phone").fill("650-356-8706")
    page2.get_by_test_id("additionalContact_1").get_by_label("Email– Optional").click()
    page2.get_by_test_id("additionalContact_1").get_by_label("Email– Optional").fill("")
    page2.get_by_text("(2) Fire (9) Elevators and additional CPE connected to POTS lines i.e., Voice, F").click()
    page2.get_by_text("(2) Fire (9) Elevators and additional CPE connected to POTS lines i.e., Voice, F").click()
    page2.get_by_text("(edit as needed and delete this line)").click()
    page2.get_by_text("Service Description - Standard Site SurveyEstimated WO Time: 1 hour minimum - 2 ").fill("Service Description - Standard Site Survey\n\nEstimated WO Time: 1 hour minimum - 2 hours maximum. \n\n*NOTE - Time can be added with customer approval.\n\nThis work requires experience and advanced knowledge of low voltage wiring, tone, trace, tag and testing of analog phone lines. The job focus is a POTS to Wireless Site Survey.\n\nYou will be responsible for conducting the Site Survey for the installation of:\n\n(2) Fire (9) Elevators and additional CPE connected to POTS lines i.e., Voice, Fax, Intercom, etc. \n\n(\n\nWe are looking to install a physical Enclosure (2'x2') that contains a CradlePoint router, ATA, UPS, and an attached 66-Block.\n\nNOTE - All the equipment will be activated, configured, and secured inside the Enclosure once shipped to the site.\n\nThe Enclosure and 66-block will be installed onto a plywood backboard in the customer's Telco Room/MPOE/IDF. Once the Enclosure is mounted, a connection is needed from our 66-block to the application service. The various applications installed for this Solution can be Fire/Burglar, Elevator, Voice, Modem and Fax.\n\nNOTE - The assigned provider is the only authorized individual to complete the work. Should there be a change in technician, this change must be pre-approved and re-assigned via the Field Nation application.\n\nScope of Work Details:\n\nOnce you accept this job, below are the details of the expectations for this effort:\n\nEquipment Required:\n\nAnalog Phone and/or Butt Set that can Monitor calls.\n66/110 Punch down tool and Cable Tester/Toner.\nCell phone with photo capability.\nPermanent Marker with fine tip or labeler.\nTelephone wire and connectors.\nDrill and appropriate tools for mounting equipment.\nScrews and/or washers to mount the enclosure to the backboard.\nApplicable Cellular Signal application for Signal/Speedtest.\nMASK optional\n\n Tasks\n\nOnce Onsite:\n\nCheck-in using the Field Nation application.\nMeet with Customer Contact to identify MPOE or any Telco type rooms, and locations where phone equipment will be located.\nCall into the bridge call number provided to get verbal instruction from MACH Activations. Alternate number Technical Support 1-866-972-7677 x4.\nOnce you’re at the MPOE, locate space to install the Enclosure on the backboard.\n\n(2x2 enclosure with 66-block with a dedicated power outlet within 6’ is required.)\n\nTake pics of the backboard and surrounding areas. Upload to Fiend Nation.\nYou will be testing for Cellular Signals in the area where you'll be mounting the Enclosure. *Utilize your cell phone and/or laptop for Speedtest and any other app you might have to show signal strength and provide the carrier.\nTone, trace and tag all POTS lines associated to CPE we may be installing. Provide TNs.\nVerify functionality of previous lines (dial tone (DT) is required - inbound/outbound calling.\nVerify functionality of customer equipment to identify faults in CPE or inside wiring. If faults are found notify MACH Activations.\nConduct testing of the cab buttons to verify they are calling out properly. Confirm with MACH Activations.\nTake pictures of the full background of the installation location and all associated areas and CPE. Upload to Field Nation.\nMake any additional equipment recommendations based on Cellular signals, (i.e., Indoor/Outdoor antenna, cable length and any mounting brackets.)\nProvide any site recommendation changes, challenges like basement block/concrete walls, metal roof etc. to MACH Activations Technician.\n\n \n\nOther:\n\nCheck out using the Field Nation.\nEnter your Close out notes and Close out job in Field Nation.\nMake sure you clean up. Leave the space neat!")
    page2.get_by_test_id("approxHoursInput").click()
    page2.get_by_test_id("approxHoursInput").fill("1")
    page2.get_by_test_id("Save as Draft").click()
    page2.goto("https://app.fieldnation.com/workorders/13721184")
    page2.close()
    page1.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
